# Generated by Django 6.0.5 on 2026-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_course_level_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='student_profiles/'),
        ),
    ]
